language: node_js
node_js:
  - "node"
script: echo "Running tests against $(node -v)..."
env:
  - ARTIFACTS_PATHS="./test-report.html"
  - CAN_FAIL=false
jobs:
  allow_failures: 
    env:
      - CAN_FAIL=true
  include:
    - stage: Linting & Test & Report
      script: 
        - npm run lint > lint.txt
        - jest --coverage && cat ./coverage/lcov.info | coveralls
        - coveralls < coverage/lcov.info
      env:
        - CAN_FAIL=true
      on:
        tags

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "./test-report.html"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
