language: node_js
node_js:
  - "node"
script: echo "Running tests against $(node -v)..."
env:
  - ARTIFACTS_PATHS="./test-report.html"
  - CAN_FAIL=false
jobs:
  allow_failures: 
    env:
      - CAN_FAIL=true
  include:
      script: 
        - npm run lint > lint.txt
        - jest --coverage && cat ./coverage/lcov.info | coveralls
        - coveralls < coverage/lcov.info
        - ls

      env:
       - CAN_FAIL=true
      
      api_key: '$GITHUB_API_KEY'
      file: 
        - 'test_report.html' 
        - 'lint.txt'
      skip_cleanup: true
      on:
        tags
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    make web
    cd web
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://saurtm12:$GITHUB_API_KEY@github.com/saurtm12/software_testing_course_assignment-gh-pages gh-pages &>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi