language: node_js
node_js:
  - "node"
script: echo "Running tests against $(node -v)..."

jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  
  include:
    - stage: Linting and Test and Report
      script: npm run lint
      env:
        - CAN_FAIL=true
      
    - stage: Test and Report
      env:
        - CAN_FAIL=true
      script: jest --coverage || cat ./coverage/lcov.info | coveralls 
