language: node_js
node_js:
  - "node"
script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Linting and Test and Report
      script: 
        npm run lint > lint.txt &&
        jest --coverage && cat ./coverage/lcov.info | coveralls &&
        coveralls < coverage/lcov.info
